### ISSUE TITLE
A user can modify tasks they have already added

### ISSUE THREAD

**Issue by benjaminheng** [cs2103aug2015-f11-2j/main#14]
... so that the user can make changes without deleting and readding the task.

Example:
`edit <ID> by <date> <time>` - set new deadline
`edit <ID> <task>` - change task description
`edit <ID> from <date> <time> to <date> <time>` - set new start/end dates.

Aliases:
edit, update

**Comment by tanweijun** [comment]
Implemented in b8b46ee32e82998bba9ad0eee626c9e54d7425a1
