### ISSUE TITLE
Ability to mark task as complete or incomplete

### ISSUE THREAD

**Issue by mingxuanlee** [cs2103aug2015-f11-2j/main#18]

**Comment by benjaminheng** [comment]
Added to v0.1 because this is a prerequisite of #26, which is scheduled for v0.1.

**Comment by benjaminheng** [comment]
Command:
`done <ID>[,<ID>,...]`

Shall we have the command toggle the completed state of the task or have a separate command to mark as undone? eg. `undone`

**Comment by tanweijun** [comment]
I support toggle.

**Comment by tanweijun** [comment]
Seems more logical to do toggle, but we will need to change the keyword. Maybe something like mark instead of done?

**Comment by benjaminheng** [comment]
Yeah I'm in favor of toggling. I think `mark` is good.

**Comment by tanweijun** [comment]
Completed. ec73e7e13706963c52972bf803e78a486a549f35
