### ISSUE TITLE
Ability to view recent actions

### ISSUE THREAD

**Issue by mingxuanlee** [cs2103aug2015-f11-2j/main#21]
To allow easy undo/revert

**Comment by benjaminheng** [comment]
Is this like a `history` command?

**Comment by mingxuanlee** [comment]
Yes, is `history` part of an existing user story? If so let's close this.

**Comment by benjaminheng** [comment]
Nope it's not, just clarifying.

Anyway I realize we're missing a user story for the undo feature.

**Comment by mingxuanlee** [comment]
But I think we have a delete feature, so let's put this undo as medium and use delete as the core functionality for now?

**Comment by benjaminheng** [comment]
Ok. Delete is in v0.1 and undo is issue #35. Maybe put undo in v0.2.

**Comment by benjaminheng** [comment]
I'm gonna close this in favor of #69
