### ISSUE TITLE
Detailed help for each command

### ISSUE THREAD

**Issue by mingxuanlee** [cs2103aug2015-f11-2j/main#22]
With usage examples

**Comment by benjaminheng** [comment]
e.g. `help add` for detailed usage examples for the `add` command.

**Comment by subo23** [comment]
User can enter help "function"; for example help add/help delete/edit...etc 
if the function does not exist, show all.

Deployed to undo branch.

**Comment by benjaminheng** [comment]
If command doesn't exist, should preserve current state.

**Comment by benjaminheng** [comment]
Have you pushed? I don't see it. Anyway undo is already merged with master, make a new branch for it

**Comment by subo23** [comment]
hmm...weird.
i branch out from undo can?
