### ISSUE TITLE
A user can sort tasks

### ISSUE THREAD

**Issue by BCDarkKnight** [cs2103aug2015-f11-2j/main#32]
... so that the user can view the list of tasks based on his preferences.

**Comment by benjaminheng** [comment]
Not really necessary I think. I think as long as we have sane defaults, should be good enough for the user.

**Comment by benjaminheng** [comment]
Program currently sorts using the following: [Task.java](https://github.com/cs2103aug2015-f11-2j/main/blob/fc8da52207c80935d3333488e8706289d2203bd3/src/app/model/Task.java#L99-L143)

Should be sane enough for most users, so I'll close this for now
