### ISSUE TITLE
Think of a name for the program

### ISSUE THREAD

**Issue by benjaminheng** [cs2103aug2015-f11-2j/main#33]
Some suggestions:
- Task Manager <-- super original
- Next Up (or just **Next**)
- EasyTodo | EzTodo
- Ming Xuan's Glorious Task Manager
- Tusk
- RemindMe
- Tracker

**Comment by mingxuanlee** [comment]
TSK

**Comment by subo23** [comment]
docket

**Comment by benjaminheng** [comment]
Settled on Next
