### ISSUE TITLE
Functionality to write tasks to storage

### ISSUE THREAD

**Issue by benjaminheng** [cs2103aug2015-f11-2j/main#43]

**Comment by benjaminheng** [comment]
Just to help get things started. Something like this?

I think either a class with exposed static methods or a class implementing the [singleton](https://en.wikipedia.org/wiki/Singleton_pattern) pattern, whichever you think is more appropriate.

static:

``` java
class TaskStorage {
    public static void writeTasks(TaskList taskList) { ... }
    public static TaskList readTasks() { ... }
}
```

singleton:

``` java
class TaskStorage {
    private static TaskStorage taskStorage;

    // constructor
    private TaskStorage() {
        // initialize stuff here
    }

    public static TaskStorage getInstance() {
        if (taskStorage == null) {
            taskStorage = new TaskStorage();
        }
        return taskStorage;
    }

    public void writeTasks(TaskList taskList) { ... }
    public TaskList readTasks() { ... }
}
```

**Comment by BCDarkKnight** [comment]
Do I store the tasks as json using gson?

**Comment by benjaminheng** [comment]
Yup. Stick the .jar in a `lib/` directory in the root directory (outside `src/`). Eclipse should automatically add it to the build path.

Try to serialize the entire TaskList object, so when you read from the file you can just call `TaskList list = gson.fromJson(json, TaskList.class)`. If not possible or overly complex, then its ok, find some other way!

**Some additional stuff:**

https://sites.google.com/site/gson/gson-user-guide#TOC-Collections-Examples - shows how to serialize and deserialize a list of custom objects (ArrayList<Task> in our case)

http://stackoverflow.com/questions/5813434/trouble-with-gson-serializing-an-arraylist-of-pojos - see answer

EDIT: Actually from one of the answers (below) it sounds like gson should be able to serialize/deserialize the TaskList object out of the box.

> @ColinD What if List<TestObject> is nested in another class? How does the use of Type apply in that case to deserialize using something like MyCustomClass obj = gson.fromJson(json, MyCustomClass.class) –  raffian Oct 8 '13 at 15:13
> 1    
> 
> @raffian: Do you mean if MyCustomClass has a List<TestObject> field that needs to be deserialized? If so, there's no problem... Gson can see that the type of the field is List<TestObject> statically and deserialize the list based on that. –  ColinD Oct 8 '13 at 19:49 

---

Also can refer to https://github.com/cs2103jan2015-t13-3j/main/blob/master/src/taskcommando/storage/TaskStorage.java

notes about the above:
- they use the singleton pattern
- they read and write individual Task objects rather than the entire list

**Comment by BCDarkKnight** [comment]
It is not possible to serialize the entire TaskList object because it uses ObservableList instead of java List. The gson returns an ArrayList and cannot be converted to ObservableList.

I added another constructor in the TaskList object to allow the storage to set the ObservableList from an ArrayList.
Or do you want to just read and write individual Task objects?

**Comment by benjaminheng** [comment]
You can convert an arraylist (or any other List subclass) to observablelist using `FXCollections.observableArrayList(Collection<? extends E> col)`

https://docs.oracle.com/javase/8/javafx/api/javafx/collections/FXCollections.html

EDIT: nevermind, I think I understand the problem. Yeah, if the new constructor works, then it's fine!

**Comment by benjaminheng** [comment]
~~Here's a solution using a custom deserializer for ObservableList fields~~

~~https://gist.github.com/benjaminheng/16dd2b585e23330982d4~~

EDIT: Nevermind, I just saw your commit. Also very elegant, so it's not necessary to change!
