### ISSUE TITLE
A user can search for tasks by specifying keyword(s) found in the task description

### ISSUE THREAD

**Issue by subo23** [cs2103aug2015-f11-2j/main#5]

**Comment by mingxuanlee** [comment]
More or less done [a7784ec](https://github.com/cs2103aug2015-f11-2j/main/commit/a7784ecb652f183a0b19d2ec20a70ca5de40dded)

**Comment by benjaminheng** [comment]
https://gist.github.com/benjaminheng/b041221748f497a29b4e

Was playing with Java 8 features and realized that predicates make makes search super elegant. Implementing it this way is real simple and easy to extend.

Basically you have a list of predicates, and you add predicates to the list as required. Then compose the list into a single predicate (line 103) and apply that single predicate to the task list (L107).

**Comment by benjaminheng** [comment]
eg. 
- if user specifies type = completed, then add a predicate (t -> t.isCompleted() == true)
- if user specifies content contains "hello world", then add (t -> t.getContent().contains("hello world"))
- if user wants to display tasks before endDate, then add (t -> t.getEndDate() < endDate)

Apply all these predicates to the tasklist, and you have your results. No need for nested loops or filtering fields one by one

**Comment by mingxuanlee** [comment]
[predicate-d](https://github.com/cs2103aug2015-f11-2j/main/commit/110ee6cd7fd2d6c399245919d945e60d82f69792)
