### ISSUE TITLE
Make dates more distinctive in the task list

### ISSUE THREAD

**Issue by benjaminheng** [cs2103aug2015-f11-2j/main#53]
Colorize the dates?
- Overdue (end < now): red
- Ongoing (start < now < end): green?
- Default (now < deadline || now < start): blue? black?

**Comment by mingxuanlee** [comment]
Sounds good!

**Comment by tanweijun** [comment]
Yea, this seems good. I prefer blue for Default since Black can be confusing when looked with grey used for marking.

**Comment by BCDarkKnight** [comment]
For task such as from today to tomorrow, the end date at the right can also display tomorrow.

The headers and the end dates at the right are not in the same format seems very hard to convert. Can try to include the short format in the header and maybe show the day of the week in the header too.

**Comment by benjaminheng** [comment]
Day of week in the header is a good idea!

> One of Jim's requirements is that he wants to be able to view his schedule at a glance (paraphrased).

With respect to the above, the reason why I used a generic "dd/MM/yy" format for the item dates is for predictable dimensions. Having varying widths makes visually parsing the dates very difficult. The long date format also takes up a loooot of space (while leaving lots of unused whitespace up top)! Predictability is also the reason why I use "hh:mma" instead of "h:mma" for the time. 

I'm kinda adverse to cluttering up the header too much. A long date format already takes up a pretty substantial amount of space. The long date format is used so Jim can easily read what date it is, btw. (plus, the year is shown if a task is scheduled on a different year from now). I think adding DOW to the header is good, but additional date formats are not feasible.

**Comment by benjaminheng** [comment]
Added DOW in 3278a6dba1f1c130254a04b523f01e42fc80c83c. Closing
