### ISSUE TITLE
Make completed tasks more distinct

### ISSUE THREAD

**Issue by benjaminheng** [cs2103aug2015-f11-2j/main#56]
Strikethrough and reduced opacity isn't distinctive enough. Any ideas on how to make it so?

Current:

![sample](http://i.imgur.com/emGKy4j.png)

**Comment by benjaminheng** [comment]
How about this?

![new](http://i.imgur.com/f0WeWjJ.png)

**Comment by mingxuanlee** [comment]
How about extending the strikethrough to the datetime parameters on the right as well? 
Or greying out the datetime?

**Comment by benjaminheng** [comment]
Current:

![new](http://i.imgur.com/21SsUiQ.png)

**Comment by tanweijun** [comment]
what if we change the background color as well? for example grey or something, but that would require the base color to change as well.

**Comment by benjaminheng** [comment]
Yup, that's a problem. Greying the task should work well if the rest of the tasks were of a more contrasting color (so the light grey will look like something inactive). But grey against white is kinda contrasting for the wrong reasons IMO, makes it stand out more.

I think. I'll try and see how it looks.

**Comment by BCDarkKnight** [comment]
When the display is set to pending and tasks are mark as completed, the completed tasks should display the strike through etc for like 0.5s then moved to completed view so that the user don't have to type display pending again. Same for marking as uncompleted.

**Comment by benjaminheng** [comment]
@fionachang This feature (mark completed, wait 0.5, remove from display) is no longer feasible since architecture update to decouple the view from the controller. At least not without some pretty drastic hacking.

I'm just gonna leave the marked tasks displayed, which also allows the user to easily unmark a task if they did it by accident.
