### ISSUE TITLE
Some enhancements to marking tasks as (un)completed

### ISSUE THREAD

**Issue by benjaminheng** [cs2103aug2015-f11-2j/main#58]
Some ideas to make it more usable:
- Allow user to delimit IDs by spaces as well. `mark 1 3 4` is easier to type than `mark 1,3,4`
- Upon successful marking, tell user which tasks were marked as completed and which were uncompleted. 
  - Instead of "Marked task(s) by id: 1, 3, 4", 
  - have something like "Completed tasks: 1, 3; Uncompleted task: 4"
- Also pluralize the word "task" rather than always having "task(s)". pseudocode below

``` python
def pluralize(count, singular, plural=null):
    if count == 1:
        return singular
    elif plural:
        return plural
    return singular + "s"

pluralize(1, "task") # task
pluralize(3, "task") # tasks
pluralize(3, "box", "boxes") # boxes
```

Less important stuff:
- Magic strings [here](https://github.com/cs2103aug2015-f11-2j/main/blob/3f9f8b76a94035ea5426d73c2d42cb28c51ec60a/src/app/helper/CommandParser.java#L543). An enum type would be more appropriate.
- Awkward and non-idiomatic way to indicate failure [here](https://github.com/cs2103aug2015-f11-2j/main/blob/3f9f8b76a94035ea5426d73c2d42cb28c51ec60a/src/app/helper/CommandParser.java#L517). How about just returning null or throwing an exception?
- In CommandMark.execute(), maybe catch IndexOutOfRange exceptions to display a more descriptive error ("no task with ID <ID>") rather than letting it fall through to the catch-all block.

**Comment by tanweijun** [comment]
Noted. For the mark delimit by spaces, should I let the user use a combination of comma and space? For example mark 1, 2 3 would mark 1, 2 and 3. It feels more logical to be consistent to me, but doing that feels flexible.

**Comment by benjaminheng** [comment]
I think that's fine! Just stick the pluralize function in the commandparser for now. I'm gonna refactor commandparser into more focused classes soon. Generic methods like getFirstWord() and pluralize() will get moved to a Common class or something

**Comment by tanweijun** [comment]
Done with 37db44b9a0c437a5af1e28eee65a779907d4b273 
However feedback for invalids IDs entered still does not specifically state which ID is invalid.
