### ISSUE TITLE
Refactor program to decouple components from one another

### ISSUE THREAD

**Issue by benjaminheng** [cs2103aug2015-f11-2j/main#60]
Components should not be referencing each other both ways. 

Will involve a lot of refactoring, so get ready to resolve conflicts! (eg. [meld](http://meldmerge.org/))

**Comment by tanweijun** [comment]
Okay. Looking forward to it.

**Comment by benjaminheng** [comment]
Implemented in [architecture-update/ben](https://github.com/cs2103aug2015-f11-2j/main/commits/architecture-update/ben). Help me to test for bugs. Add, mark, display tasks; with and without valid commands, in various sequences, or any other weird stuff you can think of.

**Changes & explanation:**
- Added model: ViewState
  - Contains a snapshot of the state of the view (UI).
  - Fields like: header, status, tasklist, theme
- Change Command's `void execute()` to `ViewState execute(ViewState previousViewState)`
  - Each command object will now **return a new state**. Don't modify the previous state!
  - I've updated the command objects, so just have a look for examples. It's actually _more_ simple now (and intuitive!).
  - **Note:** You have to set isExecuted when your command executes successfully, so the controller knows. See updated command objects for examples.
- After the controller gets the ViewState returned from the command, it merges the new state with the current state, replacing any fields that changed. The current state is then returned to the view manager.
- The view simply updates the view based on the ViewState returned from the controller.

**Why not modify previousViewState in the command?**

A nice side effect from using states is that undo becomes really easy, I think. Save the previous state in the command object, and the undo function will simply return that previous state. Tada, command undone! (disclaimer: works best on commands that don't modify master. eg. display, search, theme, etc)

**Comment by benjaminheng** [comment]
Merged to master with 3525c352ce023f8a5af687617d8ab868c94c40b7
