### ISSUE TITLE
Update controller to read/write to storage

### ISSUE THREAD

**Issue by benjaminheng** [cs2103aug2015-f11-2j/main#62]
- Read from storage to the master task list upon initialization.
- Write to storage from master task list after each command.

I've updated ViewManager to accept the initialized task list from the currentViewState already, so there shouldn't be any issues. The view is basically ready and waiting for the logic component now.

Anyone feel free to implement it.

**Comment by BCDarkKnight** [comment]
Updated above including writing selected theme but not the reading of selected theme during initialization.

Currently, the app shows all tasks by default. I think it should show uncompleted tasks instead. Jim can decide what to do next immediately after launching the app instead of having many completed tasks due weeks ago showing up.

**Comment by benjaminheng** [comment]
Good point. Maybe have a method called `initializeViewState` or something, which does the following:
1. Read tasks from storage to master
2. Sets the task list in `currentViewState` to uncompleted tasks from master
3. Sets the header to read "displaying uncompleted tasks"
4. Read theme from storage to `currentViewState`

Also, do you think it'll be better to just stick `.writeTasks(master)` after `cmd.execute(...)`? Then each Command object that modifies master won't have to individually write to storage, and the TaskStorage class will only be associated with the controller rather than Command objects as well.

I understand that this decoupling is not feasible for AppStorage though, since the `saveto` command will have to modify the save location.

**Comment by BCDarkKnight** [comment]
But for commands like display and search, they don't make changes to masterTaskList so it is not necessary to write to storage again.

I was thinking about changing saveto to set [save | log] [directory path]. I have a default properties method in AppStorage, do you think I should include it in the command? If the user choose to set properties back to default, the theme might change.

**Comment by benjaminheng** [comment]
Fair enough.

`set` is kinda ambiguous I feel. When trying to specify a save location, `set` is a bit unintuitive, people would normally try typing `save` first

How about `save [log] <path>`? If "log" is not specified, the path is set as the save location, else it's set as the log file location. Maybe allow the user to specify "default" as the path, which will reset either the save or log file location to its default.
