### ISSUE TITLE
Mark command can mark the same task multiple times in the same command

### ISSUE THREAD

**Issue by benjaminheng** [cs2103aug2015-f11-2j/main#65]
For instance, `mark 1, 1` will mark the first task twice, effectively negating the operation.

Quick fix (do own research first tho!):

``` java
List<T> noDupes = new ArrayList<>(new LinkedHashSet<>(listWithDupes));
```

**Comment by tanweijun** [comment]
Fixed in 1c7d041434ce4797c2e79af3bae90f9b0f24120b
