### ISSUE TITLE
Allow edit command to remove priority and change task type

### ISSUE THREAD

**Issue by tanweijun** [cs2103aug2015-f11-2j/main#68]
So that user can remove priority from a task or change a task with a deadline or date range into a floating task.

Current edit command does not allow you to remove priority levels once you have set it. Tasks with date also cannot be set as a floating task because the date cannot be removed. This is because the current code for edit only parses what to change. If nothing is specified, nothing will be changed. The user cannot specify to change priority or date to nothing.

**Comment by benjaminheng** [comment]
I'll work on extending the parser to include the following syntax: `date none` and `priority none`.

**Comment by tanweijun** [comment]
For date instead of date none, how about just using the keyword none, and they can use by none due none or from none to none?

**Comment by benjaminheng** [comment]
Much more involved then just using "<keyword> <arg>".

Plus that method will result in the same problem, since the date is either
parsed as something or nothing. "none" is completely indistinguishable from
"sjdgduejerh": they both get parsed as null.

**Comment by tanweijun** [comment]
Done. e085b49892535a2d9f8f81ca5341450735158e06
