### ISSUE TITLE
Enhancements to search command

### ISSUE THREAD

**Issue by benjaminheng** [cs2103aug2015-f11-2j/main#72]
- Make `<keyword>` optional, so user can search for all tasks after a certain date, or all high priority tasks, for instance.
- Would having the default type be `uncompleted` be more sensible?
- The predicate builders can be moved to a separate class under `app.util` i think. Have each builder be a static method, so you call it by `predicates.add(Predicate.priorityEquals(...))`
- Wrap the [following](https://github.com/cs2103aug2015-f11-2j/main/blob/master/src/app/logic/command/CommandSearch.java#L42-L69) in a try-catch, so if anything goes wrong, at least the viewState will still be returned and the user gets a error message.

**Comment by mingxuanlee** [comment]
Done all in [c19fb47](https://github.com/cs2103aug2015-f11-2j/main/commit/c19fb471e293c1a12271acba8a3f43868e6e8397) except for the keyword optional portion. 

If keyword is made optional, does that imply that when keyword is not found, one of the secondary parameters should then be mandatory (only in this particular search type) ?

**Comment by benjaminheng** [comment]
Yup, basically the "no search parameters" error is displayed if _nothing_ is specified at all (eg. the user just types `search`). Don't think of it as primary vs secondary parameters, just think of them as individual parameters.

Off the top of my head you can do it like this: for every field that exists (content, startdate, enddate, priority, contenttype), add the appropriate predicate. If the length of predicates at the end is still 0, then nothing was found and you can display the error.

Oh yeah, and I think currently it searches for the full word delimited by spaces? I feel that doing a `.contains(...)` search is better. It was a bit unintuitive the first time I tested because i kept trying to search for "2103" and wondering why it wasn't working. Turned out I needed to specify "cs2103"
