### ISSUE TITLE
Search for date range and date after a certain date does not work for task with only a deadline

### ISSUE THREAD

**Issue by tanweijun** [cs2103aug2015-f11-2j/main#73]
search [keyword] between [date] and [date] 
search [keyword] after [date]

The 2 commands above currently does not work if the task to be searched only has a deadline. No result will be returned even if the task is in the date range. However, the command works if the task have both a start and end date and is within date range.

**Comment by mingxuanlee** [comment]
Interesting, git auto closes issues when I specify the # in the title of a commit

**Comment by benjaminheng** [comment]
Yup! https://help.github.com/articles/closing-issues-via-commit-messages/

Fun fact, if you include "fixes #xx" or "closes #xx" in a pull request, then it will close the issue too once it's merged!
