### ISSUE TITLE
Refactor CommandEdit to not call CommandParser in execute

### ISSUE THREAD

**Issue by tanweijun** [cs2103aug2015-f11-2j/main#75]

**Comment by tanweijun** [comment]
Would it be a good idea to add a displayId field in the Command abstract class just to store the display id of the task to be edited, considering that it would probably be the only command method to use it? Currently Command abstract class has no field to store Id, therefore i can only parse the Id of the task to be edited in the CommandEdit's execute method itself.

**Comment by benjaminheng** [comment]
I think if you want to, you can hack it like this
1. Add a `displayId` field to `CommandEdit` instead of `Command`
2. Add the parsing to `CommandController.parseCommand(Command cmd)`
   
   ``` java
   CommandEdit e = (CommandEdit) cmd;
   // parse display id here
   e.setDisplayId(parsedId)
   e.setContent(parsedContent)
   ```

I don't know if this even works, but it seems sound

**Comment by tanweijun** [comment]
Sounds good if it works, I'll try it.

**Comment by tanweijun** [comment]
It works! 250faee1187094dc50bec8ff199e1343e64a4128
