### ISSUE TITLE
Common.removeFirstWord() method causes error if the input is a special character

### ISSUE THREAD

**Issue by tanweijun** [cs2103aug2015-f11-2j/main#77]
Not all special characters are affected, but characters such as ' + ' and ' ? ' which is suppose to be used as aliases for commands will cause an error.

**Comment by benjaminheng** [comment]
Probably cause they're being interpreted as regex params. Wrapping it in `Pattern.quote` should fix it.

```
word = Pattern.quote(getFirstWord(commandString));
return commandString.replaceFirst(word, "")
```

**Comment by tanweijun** [comment]
Fixed by editing code as you mentioned. b3d89af56173129dc32770bdef24713a8d3d1fcd
