### ISSUE TITLE
Scroll to top after a display command

### ISSUE THREAD

**Issue by tanweijun** [cs2103aug2015-f11-2j/main#82]
Currently it is scrolled to bottom if it is already at bottom, since higher priority tasks are on top, we should scroll it to top automatically.

**Comment by benjaminheng** [comment]
Updated view logic to scroll to top of task list in branch 'issue-82'. To trigger the scrolling to top, the command should add an Action (ActionType=SCROLL_TO_TASK_LIST_TOP) to the returned ViewState.

**Comment by tanweijun** [comment]
Thanks. Done. 930527b590a84adbb6c6b3b958fc09179d92626e
