### ISSUE TITLE
Search between dates without keyword parameter does not work v0.3

### ISSUE THREAD

**Issue by tanweijun** [cs2103aug2015-f11-2j/main#83]

**Comment by benjaminheng** [comment]
What does this mean?

**Comment by tanweijun** [comment]
search between today and tmr (let's say i have tasks in that range) gives an error message for delete.

**Comment by benjaminheng** [comment]
For delete?

**Comment by tanweijun** [comment]
Yes, error for the delete command. There could be some other error there too because there shouldn't be an error.
