### ISSUE TITLE
Enhance help list UI.

### ISSUE THREAD

**Issue by subo23** [cs2103aug2015-f11-2j/main#95]

**Comment by benjaminheng** [comment]
This is a view component feature though.

**Comment by subo23** [comment]
make a overview list after user enter help.

## eg:

1   Find job  
............................................................................................
22 December, Tuesday
............................................................................................
2   MEDIUM      Do tutorial 2       by 10:00pm
3   HIGH        Quiz                12:00pm to 02:00pm
............................................................................................
22 December, Tuesday
............................................................................................
4   LOW                Physic Quiz          by 02:00am

## 5                           Gym                 03:00pm to 04:00pm

then show the example of the usage and the outcome of using the command.

[example]: delete 1 3 5

## [outcome]:

## 22 December, Tuesday

1   MEDIUM      Do tutorial 2       by 10:00pm
2   HIGH        Quiz                12:00pm to 02:00pm

**Comment by benjaminheng** [comment]
If you mean what I think you mean, it's not feasible because it will involve heavily modifying the layout. Easily a 10+ hour job including research, design and testing, not to mention having to refactor all the help strings.

\+ i think it'll be very cluttered.
