### ISSUE TITLE
Collate files

### ISSUE THREAD

**Issue by benjaminheng** [cs2103aug2015-f11-2j/main#97]
Update this when a file is fully tagged.
- [x] **app**
  - [x] Main.java
  - [x] **constants**
    - [x] CommandConstants.java
    - [x] HelpConstants.java
    - [x] StorageConstants.java 
    - [x] TaskConstants.java 
    - [x] ViewConstants.java 
  - [x] **logic**
    - [x] CommandController.java 
    - [x] **command**
      - [x] Command.java 
      - [x] CommandAdd.java 
      - [x] CommandDelete.java 
      - [x] CommandEdit.java 
      - [x] CommandExit.java 
      - [x] CommandHelp.java 
      - [x] CommandInvalid.java 
      - [x] CommandMark.java 
      - [x] CommandSave.java 
      - [x] CommandSearch.java 
      - [x] CommandTheme.java 
      - [x] CommandUndo.java 
  - [x] **model**
    - [x] Action.java
    - [x] CommandList.java
    - [x] ParserToken.java
    - [x] Task.java
    - [x] TaskCell.java
    - [x] TaskList.java
    - [x] ViewState.java
  - [x] **parser**
    - [x] CommandParser.java
    - [x] DateParser.java
  - [x] **storage**
    - [x] AppStorage.java
    - [x] TaskStorage.java
  - [x] **util**
    - [x] Common.java
    - [x] LogHelper.java
    - [x] Observer.java
    - [x] Predicates.java
  - [x] **view**
    - [x] InfoViewManager.java
    - [x] InputViewManager.java
    - [x] TaskListItemViewManager.java
    - [x] TaskListViewManager.java
    - [x] TextViewManager.java
    - [x] ViewManager.java
  - [x] **css**
    - [x] base.css
    - [x] theme_dark.css
    - [x] theme_light.css
  - [x] **fxml**
    - [x] InfoView.fxml
    - [x] InputView.fxml
    - [x] RootView.fxml
    - [x] TaskListItemView.fxml
    - [x] TaskListView.fxml
  - [x] **tests**
    - [x] CommandParserTest.java
    - [x] CommandTest.java
    - [x] CommonTest.java
    - [x] DateParserTest.java
    - [x] LogHelperTest.java
    - [x] PredicatesTest.java
    - [x] StorageTest.java
  - [x] **integration**
    - [x] IntegrationTest.java

**Comment by benjaminheng** [comment]
`@@author <matric>` - code you wrote
`@@author generated` - generated code

The `@@author` tag should appear only at the beginning of the code a person wrote. The code up to the next `@@author tag` or the end of the file (whichever comes first) will be considered as was written by that author. **So if you wrote the whole file, just tag the top of the file, otherwise you'll need to tag each individual block of code you did in that file.**

Tag the files you contributed to. When it's obvious that everything in the file is tagged, go ahead and update that checklist.

**Comment by benjaminheng** [comment]
Identified some areas for collation. In eclipse go to `window > show view > tasks`. 
![capture](https://cloud.githubusercontent.com/assets/409724/10963279/2c7e59f2-83da-11e5-9d07-ad02992b61a6.PNG)

**Comment by tanweijun** [comment]
all collated 7e028514c97a40b1b583594af8ea0f0a0ca49cd0
