### ISSUE TITLE
Unit test failing for `tests.CommandTest.testCommandSave`

### ISSUE THREAD

**Issue by benjaminheng** [cs2103aug2015-f11-2j/main#98]
Bug? Not sure, but I can't get it to pass. I've tried removing `config.properties` and all storage files.

```
org.junit.ComparisonFailure: expected:<[Saved log file location: D:/dev/eclipse-workspace/main/testsave/]log> but was:<[IOException while deleting previous logs file: D:/dev/eclipse-workspace/main/logs/next.]log>
at tests.CommandTest.testCommandSave(CommandTest.java:689)
```

**Comment by BCDarkKnight** [comment]
The test pass for me. I tried deleting all storage, log and config files, it still works.
Maybe you are running the main program and the test at the same. The logger from the test cannot delete the previous log file since the logger from the main program is accessing the log file.

**Comment by benjaminheng** [comment]
Oh that probably explains it.
